#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="US1")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertOBIN(OBIN instance);
    partial void UpdateOBIN(OBIN instance);
    partial void DeleteOBIN(OBIN instance);
    partial void InsertOWH(OWH instance);
    partial void UpdateOWH(OWH instance);
    partial void DeleteOWH(OWH instance);
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::WindowsFormsApplication2.Properties.Settings.Default.US1ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<OBIN> OBINs
		{
			get
			{
				return this.GetTable<OBIN>();
			}
		}
		
		public System.Data.Linq.Table<OWH> OWHs
		{
			get
			{
				return this.GetTable<OWH>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OBIN")]
	public partial class OBIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AbsEntry;
		
		private string _BinCode;
		
		private string _WhsCode;
		
		private System.Nullable<char> _SysBin;
		
		private System.Nullable<int> _SL1Abs;
		
		private string _SL1Code;
		
		private System.Nullable<int> _SL2Abs;
		
		private string _SL2Code;
		
		private System.Nullable<int> _SL3Abs;
		
		private string _SL3Code;
		
		private System.Nullable<int> _SL4Abs;
		
		private string _SL4Code;
		
		private System.Nullable<int> _Attr1Abs;
		
		private string _Attr1Val;
		
		private System.Nullable<int> _Attr2Abs;
		
		private string _Attr2Val;
		
		private System.Nullable<int> _Attr3Abs;
		
		private string _Attr3Val;
		
		private System.Nullable<int> _Attr4Abs;
		
		private string _Attr4Val;
		
		private System.Nullable<int> _Attr5Abs;
		
		private string _Attr5Val;
		
		private System.Nullable<int> _Attr6Abs;
		
		private string _Attr6Val;
		
		private System.Nullable<int> _Attr7Abs;
		
		private string _Attr7Val;
		
		private System.Nullable<int> _Attr8Abs;
		
		private string _Attr8Val;
		
		private System.Nullable<int> _Attr9Abs;
		
		private string _Attr9Val;
		
		private System.Nullable<int> _Attr10Abs;
		
		private string _Attr10Val;
		
		private System.Nullable<char> _Disabled;
		
		private string _Descr;
		
		private string _BarCode;
		
		private string _AltSortCod;
		
		private System.Nullable<short> _ItmRtrictT;
		
		private string _SpcItmCode;
		
		private System.Nullable<short> _SpcItmGrpC;
		
		private System.Nullable<char> _SngBatch;
		
		private System.Nullable<short> _RtrictType;
		
		private string _RtrictResn;
		
		private System.Nullable<System.DateTime> _RtrictDate;
		
		private System.Nullable<char> _DataSource;
		
		private System.Nullable<short> _UserSign;
		
		private System.Nullable<char> _Transfered;
		
		private System.Nullable<short> _Instance;
		
		private System.Nullable<int> _LogInstanc;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<short> _UserSign2;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private System.Nullable<char> _Deleted;
		
		private System.Nullable<decimal> _MinLevel;
		
		private System.Nullable<decimal> _MaxLevel;
		
		private System.Nullable<char> _ReceiveBin;
		
		private System.Nullable<char> _NoAutoAllc;
		
		private System.Nullable<decimal> _MaxWeight1;
		
		private System.Nullable<short> _Wght1Unit;
		
		private System.Nullable<decimal> _MaxWeight2;
		
		private System.Nullable<short> _Wght2Unit;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAbsEntryChanging(int value);
    partial void OnAbsEntryChanged();
    partial void OnBinCodeChanging(string value);
    partial void OnBinCodeChanged();
    partial void OnWhsCodeChanging(string value);
    partial void OnWhsCodeChanged();
    partial void OnSysBinChanging(System.Nullable<char> value);
    partial void OnSysBinChanged();
    partial void OnSL1AbsChanging(System.Nullable<int> value);
    partial void OnSL1AbsChanged();
    partial void OnSL1CodeChanging(string value);
    partial void OnSL1CodeChanged();
    partial void OnSL2AbsChanging(System.Nullable<int> value);
    partial void OnSL2AbsChanged();
    partial void OnSL2CodeChanging(string value);
    partial void OnSL2CodeChanged();
    partial void OnSL3AbsChanging(System.Nullable<int> value);
    partial void OnSL3AbsChanged();
    partial void OnSL3CodeChanging(string value);
    partial void OnSL3CodeChanged();
    partial void OnSL4AbsChanging(System.Nullable<int> value);
    partial void OnSL4AbsChanged();
    partial void OnSL4CodeChanging(string value);
    partial void OnSL4CodeChanged();
    partial void OnAttr1AbsChanging(System.Nullable<int> value);
    partial void OnAttr1AbsChanged();
    partial void OnAttr1ValChanging(string value);
    partial void OnAttr1ValChanged();
    partial void OnAttr2AbsChanging(System.Nullable<int> value);
    partial void OnAttr2AbsChanged();
    partial void OnAttr2ValChanging(string value);
    partial void OnAttr2ValChanged();
    partial void OnAttr3AbsChanging(System.Nullable<int> value);
    partial void OnAttr3AbsChanged();
    partial void OnAttr3ValChanging(string value);
    partial void OnAttr3ValChanged();
    partial void OnAttr4AbsChanging(System.Nullable<int> value);
    partial void OnAttr4AbsChanged();
    partial void OnAttr4ValChanging(string value);
    partial void OnAttr4ValChanged();
    partial void OnAttr5AbsChanging(System.Nullable<int> value);
    partial void OnAttr5AbsChanged();
    partial void OnAttr5ValChanging(string value);
    partial void OnAttr5ValChanged();
    partial void OnAttr6AbsChanging(System.Nullable<int> value);
    partial void OnAttr6AbsChanged();
    partial void OnAttr6ValChanging(string value);
    partial void OnAttr6ValChanged();
    partial void OnAttr7AbsChanging(System.Nullable<int> value);
    partial void OnAttr7AbsChanged();
    partial void OnAttr7ValChanging(string value);
    partial void OnAttr7ValChanged();
    partial void OnAttr8AbsChanging(System.Nullable<int> value);
    partial void OnAttr8AbsChanged();
    partial void OnAttr8ValChanging(string value);
    partial void OnAttr8ValChanged();
    partial void OnAttr9AbsChanging(System.Nullable<int> value);
    partial void OnAttr9AbsChanged();
    partial void OnAttr9ValChanging(string value);
    partial void OnAttr9ValChanged();
    partial void OnAttr10AbsChanging(System.Nullable<int> value);
    partial void OnAttr10AbsChanged();
    partial void OnAttr10ValChanging(string value);
    partial void OnAttr10ValChanged();
    partial void OnDisabledChanging(System.Nullable<char> value);
    partial void OnDisabledChanged();
    partial void OnDescrChanging(string value);
    partial void OnDescrChanged();
    partial void OnBarCodeChanging(string value);
    partial void OnBarCodeChanged();
    partial void OnAltSortCodChanging(string value);
    partial void OnAltSortCodChanged();
    partial void OnItmRtrictTChanging(System.Nullable<short> value);
    partial void OnItmRtrictTChanged();
    partial void OnSpcItmCodeChanging(string value);
    partial void OnSpcItmCodeChanged();
    partial void OnSpcItmGrpCChanging(System.Nullable<short> value);
    partial void OnSpcItmGrpCChanged();
    partial void OnSngBatchChanging(System.Nullable<char> value);
    partial void OnSngBatchChanged();
    partial void OnRtrictTypeChanging(System.Nullable<short> value);
    partial void OnRtrictTypeChanged();
    partial void OnRtrictResnChanging(string value);
    partial void OnRtrictResnChanged();
    partial void OnRtrictDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRtrictDateChanged();
    partial void OnDataSourceChanging(System.Nullable<char> value);
    partial void OnDataSourceChanged();
    partial void OnUserSignChanging(System.Nullable<short> value);
    partial void OnUserSignChanged();
    partial void OnTransferedChanging(System.Nullable<char> value);
    partial void OnTransferedChanged();
    partial void OnInstanceChanging(System.Nullable<short> value);
    partial void OnInstanceChanged();
    partial void OnLogInstancChanging(System.Nullable<int> value);
    partial void OnLogInstancChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnUserSign2Changing(System.Nullable<short> value);
    partial void OnUserSign2Changed();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnDeletedChanging(System.Nullable<char> value);
    partial void OnDeletedChanged();
    partial void OnMinLevelChanging(System.Nullable<decimal> value);
    partial void OnMinLevelChanged();
    partial void OnMaxLevelChanging(System.Nullable<decimal> value);
    partial void OnMaxLevelChanged();
    partial void OnReceiveBinChanging(System.Nullable<char> value);
    partial void OnReceiveBinChanged();
    partial void OnNoAutoAllcChanging(System.Nullable<char> value);
    partial void OnNoAutoAllcChanged();
    partial void OnMaxWeight1Changing(System.Nullable<decimal> value);
    partial void OnMaxWeight1Changed();
    partial void OnWght1UnitChanging(System.Nullable<short> value);
    partial void OnWght1UnitChanged();
    partial void OnMaxWeight2Changing(System.Nullable<decimal> value);
    partial void OnMaxWeight2Changed();
    partial void OnWght2UnitChanging(System.Nullable<short> value);
    partial void OnWght2UnitChanged();
    #endregion
		
		public OBIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AbsEntry", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AbsEntry
		{
			get
			{
				return this._AbsEntry;
			}
			set
			{
				if ((this._AbsEntry != value))
				{
					this.OnAbsEntryChanging(value);
					this.SendPropertyChanging();
					this._AbsEntry = value;
					this.SendPropertyChanged("AbsEntry");
					this.OnAbsEntryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BinCode", DbType="NVarChar(228) NOT NULL", CanBeNull=false)]
		public string BinCode
		{
			get
			{
				return this._BinCode;
			}
			set
			{
				if ((this._BinCode != value))
				{
					this.OnBinCodeChanging(value);
					this.SendPropertyChanging();
					this._BinCode = value;
					this.SendPropertyChanged("BinCode");
					this.OnBinCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhsCode", DbType="NVarChar(8)")]
		public string WhsCode
		{
			get
			{
				return this._WhsCode;
			}
			set
			{
				if ((this._WhsCode != value))
				{
					this.OnWhsCodeChanging(value);
					this.SendPropertyChanging();
					this._WhsCode = value;
					this.SendPropertyChanged("WhsCode");
					this.OnWhsCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysBin", DbType="Char(1)")]
		public System.Nullable<char> SysBin
		{
			get
			{
				return this._SysBin;
			}
			set
			{
				if ((this._SysBin != value))
				{
					this.OnSysBinChanging(value);
					this.SendPropertyChanging();
					this._SysBin = value;
					this.SendPropertyChanged("SysBin");
					this.OnSysBinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL1Abs", DbType="Int")]
		public System.Nullable<int> SL1Abs
		{
			get
			{
				return this._SL1Abs;
			}
			set
			{
				if ((this._SL1Abs != value))
				{
					this.OnSL1AbsChanging(value);
					this.SendPropertyChanging();
					this._SL1Abs = value;
					this.SendPropertyChanged("SL1Abs");
					this.OnSL1AbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL1Code", DbType="NVarChar(50)")]
		public string SL1Code
		{
			get
			{
				return this._SL1Code;
			}
			set
			{
				if ((this._SL1Code != value))
				{
					this.OnSL1CodeChanging(value);
					this.SendPropertyChanging();
					this._SL1Code = value;
					this.SendPropertyChanged("SL1Code");
					this.OnSL1CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL2Abs", DbType="Int")]
		public System.Nullable<int> SL2Abs
		{
			get
			{
				return this._SL2Abs;
			}
			set
			{
				if ((this._SL2Abs != value))
				{
					this.OnSL2AbsChanging(value);
					this.SendPropertyChanging();
					this._SL2Abs = value;
					this.SendPropertyChanged("SL2Abs");
					this.OnSL2AbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL2Code", DbType="NVarChar(50)")]
		public string SL2Code
		{
			get
			{
				return this._SL2Code;
			}
			set
			{
				if ((this._SL2Code != value))
				{
					this.OnSL2CodeChanging(value);
					this.SendPropertyChanging();
					this._SL2Code = value;
					this.SendPropertyChanged("SL2Code");
					this.OnSL2CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL3Abs", DbType="Int")]
		public System.Nullable<int> SL3Abs
		{
			get
			{
				return this._SL3Abs;
			}
			set
			{
				if ((this._SL3Abs != value))
				{
					this.OnSL3AbsChanging(value);
					this.SendPropertyChanging();
					this._SL3Abs = value;
					this.SendPropertyChanged("SL3Abs");
					this.OnSL3AbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL3Code", DbType="NVarChar(50)")]
		public string SL3Code
		{
			get
			{
				return this._SL3Code;
			}
			set
			{
				if ((this._SL3Code != value))
				{
					this.OnSL3CodeChanging(value);
					this.SendPropertyChanging();
					this._SL3Code = value;
					this.SendPropertyChanged("SL3Code");
					this.OnSL3CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL4Abs", DbType="Int")]
		public System.Nullable<int> SL4Abs
		{
			get
			{
				return this._SL4Abs;
			}
			set
			{
				if ((this._SL4Abs != value))
				{
					this.OnSL4AbsChanging(value);
					this.SendPropertyChanging();
					this._SL4Abs = value;
					this.SendPropertyChanged("SL4Abs");
					this.OnSL4AbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL4Code", DbType="NVarChar(50)")]
		public string SL4Code
		{
			get
			{
				return this._SL4Code;
			}
			set
			{
				if ((this._SL4Code != value))
				{
					this.OnSL4CodeChanging(value);
					this.SendPropertyChanging();
					this._SL4Code = value;
					this.SendPropertyChanged("SL4Code");
					this.OnSL4CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr1Abs", DbType="Int")]
		public System.Nullable<int> Attr1Abs
		{
			get
			{
				return this._Attr1Abs;
			}
			set
			{
				if ((this._Attr1Abs != value))
				{
					this.OnAttr1AbsChanging(value);
					this.SendPropertyChanging();
					this._Attr1Abs = value;
					this.SendPropertyChanged("Attr1Abs");
					this.OnAttr1AbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr1Val", DbType="NVarChar(20)")]
		public string Attr1Val
		{
			get
			{
				return this._Attr1Val;
			}
			set
			{
				if ((this._Attr1Val != value))
				{
					this.OnAttr1ValChanging(value);
					this.SendPropertyChanging();
					this._Attr1Val = value;
					this.SendPropertyChanged("Attr1Val");
					this.OnAttr1ValChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr2Abs", DbType="Int")]
		public System.Nullable<int> Attr2Abs
		{
			get
			{
				return this._Attr2Abs;
			}
			set
			{
				if ((this._Attr2Abs != value))
				{
					this.OnAttr2AbsChanging(value);
					this.SendPropertyChanging();
					this._Attr2Abs = value;
					this.SendPropertyChanged("Attr2Abs");
					this.OnAttr2AbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr2Val", DbType="NVarChar(20)")]
		public string Attr2Val
		{
			get
			{
				return this._Attr2Val;
			}
			set
			{
				if ((this._Attr2Val != value))
				{
					this.OnAttr2ValChanging(value);
					this.SendPropertyChanging();
					this._Attr2Val = value;
					this.SendPropertyChanged("Attr2Val");
					this.OnAttr2ValChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr3Abs", DbType="Int")]
		public System.Nullable<int> Attr3Abs
		{
			get
			{
				return this._Attr3Abs;
			}
			set
			{
				if ((this._Attr3Abs != value))
				{
					this.OnAttr3AbsChanging(value);
					this.SendPropertyChanging();
					this._Attr3Abs = value;
					this.SendPropertyChanged("Attr3Abs");
					this.OnAttr3AbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr3Val", DbType="NVarChar(20)")]
		public string Attr3Val
		{
			get
			{
				return this._Attr3Val;
			}
			set
			{
				if ((this._Attr3Val != value))
				{
					this.OnAttr3ValChanging(value);
					this.SendPropertyChanging();
					this._Attr3Val = value;
					this.SendPropertyChanged("Attr3Val");
					this.OnAttr3ValChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr4Abs", DbType="Int")]
		public System.Nullable<int> Attr4Abs
		{
			get
			{
				return this._Attr4Abs;
			}
			set
			{
				if ((this._Attr4Abs != value))
				{
					this.OnAttr4AbsChanging(value);
					this.SendPropertyChanging();
					this._Attr4Abs = value;
					this.SendPropertyChanged("Attr4Abs");
					this.OnAttr4AbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr4Val", DbType="NVarChar(20)")]
		public string Attr4Val
		{
			get
			{
				return this._Attr4Val;
			}
			set
			{
				if ((this._Attr4Val != value))
				{
					this.OnAttr4ValChanging(value);
					this.SendPropertyChanging();
					this._Attr4Val = value;
					this.SendPropertyChanged("Attr4Val");
					this.OnAttr4ValChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr5Abs", DbType="Int")]
		public System.Nullable<int> Attr5Abs
		{
			get
			{
				return this._Attr5Abs;
			}
			set
			{
				if ((this._Attr5Abs != value))
				{
					this.OnAttr5AbsChanging(value);
					this.SendPropertyChanging();
					this._Attr5Abs = value;
					this.SendPropertyChanged("Attr5Abs");
					this.OnAttr5AbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr5Val", DbType="NVarChar(20)")]
		public string Attr5Val
		{
			get
			{
				return this._Attr5Val;
			}
			set
			{
				if ((this._Attr5Val != value))
				{
					this.OnAttr5ValChanging(value);
					this.SendPropertyChanging();
					this._Attr5Val = value;
					this.SendPropertyChanged("Attr5Val");
					this.OnAttr5ValChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr6Abs", DbType="Int")]
		public System.Nullable<int> Attr6Abs
		{
			get
			{
				return this._Attr6Abs;
			}
			set
			{
				if ((this._Attr6Abs != value))
				{
					this.OnAttr6AbsChanging(value);
					this.SendPropertyChanging();
					this._Attr6Abs = value;
					this.SendPropertyChanged("Attr6Abs");
					this.OnAttr6AbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr6Val", DbType="NVarChar(20)")]
		public string Attr6Val
		{
			get
			{
				return this._Attr6Val;
			}
			set
			{
				if ((this._Attr6Val != value))
				{
					this.OnAttr6ValChanging(value);
					this.SendPropertyChanging();
					this._Attr6Val = value;
					this.SendPropertyChanged("Attr6Val");
					this.OnAttr6ValChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr7Abs", DbType="Int")]
		public System.Nullable<int> Attr7Abs
		{
			get
			{
				return this._Attr7Abs;
			}
			set
			{
				if ((this._Attr7Abs != value))
				{
					this.OnAttr7AbsChanging(value);
					this.SendPropertyChanging();
					this._Attr7Abs = value;
					this.SendPropertyChanged("Attr7Abs");
					this.OnAttr7AbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr7Val", DbType="NVarChar(20)")]
		public string Attr7Val
		{
			get
			{
				return this._Attr7Val;
			}
			set
			{
				if ((this._Attr7Val != value))
				{
					this.OnAttr7ValChanging(value);
					this.SendPropertyChanging();
					this._Attr7Val = value;
					this.SendPropertyChanged("Attr7Val");
					this.OnAttr7ValChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr8Abs", DbType="Int")]
		public System.Nullable<int> Attr8Abs
		{
			get
			{
				return this._Attr8Abs;
			}
			set
			{
				if ((this._Attr8Abs != value))
				{
					this.OnAttr8AbsChanging(value);
					this.SendPropertyChanging();
					this._Attr8Abs = value;
					this.SendPropertyChanged("Attr8Abs");
					this.OnAttr8AbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr8Val", DbType="NVarChar(20)")]
		public string Attr8Val
		{
			get
			{
				return this._Attr8Val;
			}
			set
			{
				if ((this._Attr8Val != value))
				{
					this.OnAttr8ValChanging(value);
					this.SendPropertyChanging();
					this._Attr8Val = value;
					this.SendPropertyChanged("Attr8Val");
					this.OnAttr8ValChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr9Abs", DbType="Int")]
		public System.Nullable<int> Attr9Abs
		{
			get
			{
				return this._Attr9Abs;
			}
			set
			{
				if ((this._Attr9Abs != value))
				{
					this.OnAttr9AbsChanging(value);
					this.SendPropertyChanging();
					this._Attr9Abs = value;
					this.SendPropertyChanged("Attr9Abs");
					this.OnAttr9AbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr9Val", DbType="NVarChar(20)")]
		public string Attr9Val
		{
			get
			{
				return this._Attr9Val;
			}
			set
			{
				if ((this._Attr9Val != value))
				{
					this.OnAttr9ValChanging(value);
					this.SendPropertyChanging();
					this._Attr9Val = value;
					this.SendPropertyChanged("Attr9Val");
					this.OnAttr9ValChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr10Abs", DbType="Int")]
		public System.Nullable<int> Attr10Abs
		{
			get
			{
				return this._Attr10Abs;
			}
			set
			{
				if ((this._Attr10Abs != value))
				{
					this.OnAttr10AbsChanging(value);
					this.SendPropertyChanging();
					this._Attr10Abs = value;
					this.SendPropertyChanged("Attr10Abs");
					this.OnAttr10AbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attr10Val", DbType="NVarChar(20)")]
		public string Attr10Val
		{
			get
			{
				return this._Attr10Val;
			}
			set
			{
				if ((this._Attr10Val != value))
				{
					this.OnAttr10ValChanging(value);
					this.SendPropertyChanging();
					this._Attr10Val = value;
					this.SendPropertyChanged("Attr10Val");
					this.OnAttr10ValChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disabled", DbType="Char(1)")]
		public System.Nullable<char> Disabled
		{
			get
			{
				return this._Disabled;
			}
			set
			{
				if ((this._Disabled != value))
				{
					this.OnDisabledChanging(value);
					this.SendPropertyChanging();
					this._Disabled = value;
					this.SendPropertyChanged("Disabled");
					this.OnDisabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descr", DbType="NVarChar(50)")]
		public string Descr
		{
			get
			{
				return this._Descr;
			}
			set
			{
				if ((this._Descr != value))
				{
					this.OnDescrChanging(value);
					this.SendPropertyChanging();
					this._Descr = value;
					this.SendPropertyChanged("Descr");
					this.OnDescrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarCode", DbType="NVarChar(100)")]
		public string BarCode
		{
			get
			{
				return this._BarCode;
			}
			set
			{
				if ((this._BarCode != value))
				{
					this.OnBarCodeChanging(value);
					this.SendPropertyChanging();
					this._BarCode = value;
					this.SendPropertyChanged("BarCode");
					this.OnBarCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltSortCod", DbType="NVarChar(50)")]
		public string AltSortCod
		{
			get
			{
				return this._AltSortCod;
			}
			set
			{
				if ((this._AltSortCod != value))
				{
					this.OnAltSortCodChanging(value);
					this.SendPropertyChanging();
					this._AltSortCod = value;
					this.SendPropertyChanged("AltSortCod");
					this.OnAltSortCodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItmRtrictT", DbType="SmallInt")]
		public System.Nullable<short> ItmRtrictT
		{
			get
			{
				return this._ItmRtrictT;
			}
			set
			{
				if ((this._ItmRtrictT != value))
				{
					this.OnItmRtrictTChanging(value);
					this.SendPropertyChanging();
					this._ItmRtrictT = value;
					this.SendPropertyChanged("ItmRtrictT");
					this.OnItmRtrictTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpcItmCode", DbType="NVarChar(20)")]
		public string SpcItmCode
		{
			get
			{
				return this._SpcItmCode;
			}
			set
			{
				if ((this._SpcItmCode != value))
				{
					this.OnSpcItmCodeChanging(value);
					this.SendPropertyChanging();
					this._SpcItmCode = value;
					this.SendPropertyChanged("SpcItmCode");
					this.OnSpcItmCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpcItmGrpC", DbType="SmallInt")]
		public System.Nullable<short> SpcItmGrpC
		{
			get
			{
				return this._SpcItmGrpC;
			}
			set
			{
				if ((this._SpcItmGrpC != value))
				{
					this.OnSpcItmGrpCChanging(value);
					this.SendPropertyChanging();
					this._SpcItmGrpC = value;
					this.SendPropertyChanged("SpcItmGrpC");
					this.OnSpcItmGrpCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SngBatch", DbType="Char(1)")]
		public System.Nullable<char> SngBatch
		{
			get
			{
				return this._SngBatch;
			}
			set
			{
				if ((this._SngBatch != value))
				{
					this.OnSngBatchChanging(value);
					this.SendPropertyChanging();
					this._SngBatch = value;
					this.SendPropertyChanged("SngBatch");
					this.OnSngBatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RtrictType", DbType="SmallInt")]
		public System.Nullable<short> RtrictType
		{
			get
			{
				return this._RtrictType;
			}
			set
			{
				if ((this._RtrictType != value))
				{
					this.OnRtrictTypeChanging(value);
					this.SendPropertyChanging();
					this._RtrictType = value;
					this.SendPropertyChanged("RtrictType");
					this.OnRtrictTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RtrictResn", DbType="NVarChar(254)")]
		public string RtrictResn
		{
			get
			{
				return this._RtrictResn;
			}
			set
			{
				if ((this._RtrictResn != value))
				{
					this.OnRtrictResnChanging(value);
					this.SendPropertyChanging();
					this._RtrictResn = value;
					this.SendPropertyChanged("RtrictResn");
					this.OnRtrictResnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RtrictDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> RtrictDate
		{
			get
			{
				return this._RtrictDate;
			}
			set
			{
				if ((this._RtrictDate != value))
				{
					this.OnRtrictDateChanging(value);
					this.SendPropertyChanging();
					this._RtrictDate = value;
					this.SendPropertyChanged("RtrictDate");
					this.OnRtrictDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataSource", DbType="Char(1)")]
		public System.Nullable<char> DataSource
		{
			get
			{
				return this._DataSource;
			}
			set
			{
				if ((this._DataSource != value))
				{
					this.OnDataSourceChanging(value);
					this.SendPropertyChanging();
					this._DataSource = value;
					this.SendPropertyChanged("DataSource");
					this.OnDataSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserSign", DbType="SmallInt")]
		public System.Nullable<short> UserSign
		{
			get
			{
				return this._UserSign;
			}
			set
			{
				if ((this._UserSign != value))
				{
					this.OnUserSignChanging(value);
					this.SendPropertyChanging();
					this._UserSign = value;
					this.SendPropertyChanged("UserSign");
					this.OnUserSignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transfered", DbType="Char(1)")]
		public System.Nullable<char> Transfered
		{
			get
			{
				return this._Transfered;
			}
			set
			{
				if ((this._Transfered != value))
				{
					this.OnTransferedChanging(value);
					this.SendPropertyChanging();
					this._Transfered = value;
					this.SendPropertyChanged("Transfered");
					this.OnTransferedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instance", DbType="SmallInt")]
		public System.Nullable<short> Instance
		{
			get
			{
				return this._Instance;
			}
			set
			{
				if ((this._Instance != value))
				{
					this.OnInstanceChanging(value);
					this.SendPropertyChanging();
					this._Instance = value;
					this.SendPropertyChanged("Instance");
					this.OnInstanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogInstanc", DbType="Int")]
		public System.Nullable<int> LogInstanc
		{
			get
			{
				return this._LogInstanc;
			}
			set
			{
				if ((this._LogInstanc != value))
				{
					this.OnLogInstancChanging(value);
					this.SendPropertyChanging();
					this._LogInstanc = value;
					this.SendPropertyChanged("LogInstanc");
					this.OnLogInstancChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserSign2", DbType="SmallInt")]
		public System.Nullable<short> UserSign2
		{
			get
			{
				return this._UserSign2;
			}
			set
			{
				if ((this._UserSign2 != value))
				{
					this.OnUserSign2Changing(value);
					this.SendPropertyChanging();
					this._UserSign2 = value;
					this.SendPropertyChanged("UserSign2");
					this.OnUserSign2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Char(1)")]
		public System.Nullable<char> Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinLevel", DbType="Decimal(19,6)")]
		public System.Nullable<decimal> MinLevel
		{
			get
			{
				return this._MinLevel;
			}
			set
			{
				if ((this._MinLevel != value))
				{
					this.OnMinLevelChanging(value);
					this.SendPropertyChanging();
					this._MinLevel = value;
					this.SendPropertyChanged("MinLevel");
					this.OnMinLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxLevel", DbType="Decimal(19,6)")]
		public System.Nullable<decimal> MaxLevel
		{
			get
			{
				return this._MaxLevel;
			}
			set
			{
				if ((this._MaxLevel != value))
				{
					this.OnMaxLevelChanging(value);
					this.SendPropertyChanging();
					this._MaxLevel = value;
					this.SendPropertyChanged("MaxLevel");
					this.OnMaxLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiveBin", DbType="Char(1)")]
		public System.Nullable<char> ReceiveBin
		{
			get
			{
				return this._ReceiveBin;
			}
			set
			{
				if ((this._ReceiveBin != value))
				{
					this.OnReceiveBinChanging(value);
					this.SendPropertyChanging();
					this._ReceiveBin = value;
					this.SendPropertyChanged("ReceiveBin");
					this.OnReceiveBinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoAutoAllc", DbType="Char(1)")]
		public System.Nullable<char> NoAutoAllc
		{
			get
			{
				return this._NoAutoAllc;
			}
			set
			{
				if ((this._NoAutoAllc != value))
				{
					this.OnNoAutoAllcChanging(value);
					this.SendPropertyChanging();
					this._NoAutoAllc = value;
					this.SendPropertyChanged("NoAutoAllc");
					this.OnNoAutoAllcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxWeight1", DbType="Decimal(19,6)")]
		public System.Nullable<decimal> MaxWeight1
		{
			get
			{
				return this._MaxWeight1;
			}
			set
			{
				if ((this._MaxWeight1 != value))
				{
					this.OnMaxWeight1Changing(value);
					this.SendPropertyChanging();
					this._MaxWeight1 = value;
					this.SendPropertyChanged("MaxWeight1");
					this.OnMaxWeight1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wght1Unit", DbType="SmallInt")]
		public System.Nullable<short> Wght1Unit
		{
			get
			{
				return this._Wght1Unit;
			}
			set
			{
				if ((this._Wght1Unit != value))
				{
					this.OnWght1UnitChanging(value);
					this.SendPropertyChanging();
					this._Wght1Unit = value;
					this.SendPropertyChanged("Wght1Unit");
					this.OnWght1UnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxWeight2", DbType="Decimal(19,6)")]
		public System.Nullable<decimal> MaxWeight2
		{
			get
			{
				return this._MaxWeight2;
			}
			set
			{
				if ((this._MaxWeight2 != value))
				{
					this.OnMaxWeight2Changing(value);
					this.SendPropertyChanging();
					this._MaxWeight2 = value;
					this.SendPropertyChanged("MaxWeight2");
					this.OnMaxWeight2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wght2Unit", DbType="SmallInt")]
		public System.Nullable<short> Wght2Unit
		{
			get
			{
				return this._Wght2Unit;
			}
			set
			{
				if ((this._Wght2Unit != value))
				{
					this.OnWght2UnitChanging(value);
					this.SendPropertyChanging();
					this._Wght2Unit = value;
					this.SendPropertyChanged("Wght2Unit");
					this.OnWght2UnitChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OWHS")]
	public partial class OWH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _WhsCode;
		
		private string _WhsName;
		
		private System.Nullable<int> _IntrnalKey;
		
		private string _Grp_Code;
		
		private string _BalInvntAc;
		
		private string _SaleCostAc;
		
		private string _TransferAc;
		
		private System.Nullable<char> _Locked;
		
		private System.Nullable<char> _DataSource;
		
		private System.Nullable<short> _UserSign;
		
		private string _RevenuesAc;
		
		private string _VarianceAc;
		
		private string _DecreasAc;
		
		private string _IncreasAc;
		
		private string _ReturnAc;
		
		private string _ExpensesAc;
		
		private string _EURevenuAc;
		
		private string _EUExpensAc;
		
		private string _FrRevenuAc;
		
		private string _FrExpensAc;
		
		private string _VatGroup;
		
		private string _Street;
		
		private string _Block;
		
		private string _ZipCode;
		
		private string _City;
		
		private string _County;
		
		private string _Country;
		
		private string _State;
		
		private System.Nullable<int> _Location;
		
		private System.Nullable<char> _DropShip;
		
		private string _ExmptIncom;
		
		private System.Nullable<char> _UseTax;
		
		private string _PriceDifAc;
		
		private string _ExchangeAc;
		
		private string _BalanceAcc;
		
		private string _PurchaseAc;
		
		private string _PAReturnAc;
		
		private string _PurchOfsAc;
		
		private string _FedTaxID;
		
		private string _Building;
		
		private string _ShpdGdsAct;
		
		private string _VatRevAct;
		
		private string _DecresGlAc;
		
		private string _IncresGlAc;
		
		private System.Nullable<char> _Nettable;
		
		private string _StokRvlAct;
		
		private string _StkOffsAct;
		
		private string _WipAcct;
		
		private string _WipVarAcct;
		
		private string _CostRvlAct;
		
		private string _CstOffsAct;
		
		private string _ExpClrAct;
		
		private string _ExpOfstAct;
		
		private string _objType;
		
		private System.Nullable<int> _logInstanc;
		
		private System.Nullable<System.DateTime> _createDate;
		
		private System.Nullable<short> _userSign2;
		
		private System.Nullable<System.DateTime> _updateDate;
		
		private string _ARCMAct;
		
		private string _ARCMFrnAct;
		
		private string _ARCMEUAct;
		
		private string _ARCMExpAct;
		
		private string _APCMAct;
		
		private string _APCMFrnAct;
		
		private string _APCMEUAct;
		
		private string _RevRetAct;
		
		private System.Nullable<int> _BPLid;
		
		private System.Nullable<char> _OwnerCode;
		
		private string _NegStckAct;
		
		private string _StkInTnAct;
		
		private string _AddrType;
		
		private string _StreetNo;
		
		private string _PurBalAct;
		
		private System.Nullable<char> _Excisable;
		
		private string _WhICenAct;
		
		private string _WhOCenAct;
		
		private string _WhShipTo;
		
		private string _WipOffset;
		
		private string _StockOffst;
		
		private System.Nullable<int> _StorKeeper;
		
		private string _Shipper;
		
		private System.Nullable<char> _BinActivat;
		
		private string _BinSeptor;
		
		private System.Nullable<int> _DftBinAbs;
		
		private System.Nullable<char> _DftBinEnfd;
		
		private System.Nullable<short> _AutoIssMtd;
		
		private System.Nullable<char> _ManageSnB;
		
		private System.Nullable<short> _RecItemsBy;
		
		private System.Nullable<char> _RecBinEnab;
		
		private string _GlblLocNum;
		
		private System.Nullable<char> _RecvEmpBin;
		
		private System.Nullable<char> _Inactive;
		
		private System.Nullable<char> _RecvMaxQty;
		
		private System.Nullable<short> _AutoRecvMd;
		
		private System.Nullable<char> _RecvMaxWT;
		
		private string _RecvUpTo;
		
		private string _FreeChrgSA;
		
		private string _FreeChrgPU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWhsCodeChanging(string value);
    partial void OnWhsCodeChanged();
    partial void OnWhsNameChanging(string value);
    partial void OnWhsNameChanged();
    partial void OnIntrnalKeyChanging(System.Nullable<int> value);
    partial void OnIntrnalKeyChanged();
    partial void OnGrp_CodeChanging(string value);
    partial void OnGrp_CodeChanged();
    partial void OnBalInvntAcChanging(string value);
    partial void OnBalInvntAcChanged();
    partial void OnSaleCostAcChanging(string value);
    partial void OnSaleCostAcChanged();
    partial void OnTransferAcChanging(string value);
    partial void OnTransferAcChanged();
    partial void OnLockedChanging(System.Nullable<char> value);
    partial void OnLockedChanged();
    partial void OnDataSourceChanging(System.Nullable<char> value);
    partial void OnDataSourceChanged();
    partial void OnUserSignChanging(System.Nullable<short> value);
    partial void OnUserSignChanged();
    partial void OnRevenuesAcChanging(string value);
    partial void OnRevenuesAcChanged();
    partial void OnVarianceAcChanging(string value);
    partial void OnVarianceAcChanged();
    partial void OnDecreasAcChanging(string value);
    partial void OnDecreasAcChanged();
    partial void OnIncreasAcChanging(string value);
    partial void OnIncreasAcChanged();
    partial void OnReturnAcChanging(string value);
    partial void OnReturnAcChanged();
    partial void OnExpensesAcChanging(string value);
    partial void OnExpensesAcChanged();
    partial void OnEURevenuAcChanging(string value);
    partial void OnEURevenuAcChanged();
    partial void OnEUExpensAcChanging(string value);
    partial void OnEUExpensAcChanged();
    partial void OnFrRevenuAcChanging(string value);
    partial void OnFrRevenuAcChanged();
    partial void OnFrExpensAcChanging(string value);
    partial void OnFrExpensAcChanged();
    partial void OnVatGroupChanging(string value);
    partial void OnVatGroupChanged();
    partial void OnStreetChanging(string value);
    partial void OnStreetChanged();
    partial void OnBlockChanging(string value);
    partial void OnBlockChanged();
    partial void OnZipCodeChanging(string value);
    partial void OnZipCodeChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnCountyChanging(string value);
    partial void OnCountyChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnLocationChanging(System.Nullable<int> value);
    partial void OnLocationChanged();
    partial void OnDropShipChanging(System.Nullable<char> value);
    partial void OnDropShipChanged();
    partial void OnExmptIncomChanging(string value);
    partial void OnExmptIncomChanged();
    partial void OnUseTaxChanging(System.Nullable<char> value);
    partial void OnUseTaxChanged();
    partial void OnPriceDifAcChanging(string value);
    partial void OnPriceDifAcChanged();
    partial void OnExchangeAcChanging(string value);
    partial void OnExchangeAcChanged();
    partial void OnBalanceAccChanging(string value);
    partial void OnBalanceAccChanged();
    partial void OnPurchaseAcChanging(string value);
    partial void OnPurchaseAcChanged();
    partial void OnPAReturnAcChanging(string value);
    partial void OnPAReturnAcChanged();
    partial void OnPurchOfsAcChanging(string value);
    partial void OnPurchOfsAcChanged();
    partial void OnFedTaxIDChanging(string value);
    partial void OnFedTaxIDChanged();
    partial void OnBuildingChanging(string value);
    partial void OnBuildingChanged();
    partial void OnShpdGdsActChanging(string value);
    partial void OnShpdGdsActChanged();
    partial void OnVatRevActChanging(string value);
    partial void OnVatRevActChanged();
    partial void OnDecresGlAcChanging(string value);
    partial void OnDecresGlAcChanged();
    partial void OnIncresGlAcChanging(string value);
    partial void OnIncresGlAcChanged();
    partial void OnNettableChanging(System.Nullable<char> value);
    partial void OnNettableChanged();
    partial void OnStokRvlActChanging(string value);
    partial void OnStokRvlActChanged();
    partial void OnStkOffsActChanging(string value);
    partial void OnStkOffsActChanged();
    partial void OnWipAcctChanging(string value);
    partial void OnWipAcctChanged();
    partial void OnWipVarAcctChanging(string value);
    partial void OnWipVarAcctChanged();
    partial void OnCostRvlActChanging(string value);
    partial void OnCostRvlActChanged();
    partial void OnCstOffsActChanging(string value);
    partial void OnCstOffsActChanged();
    partial void OnExpClrActChanging(string value);
    partial void OnExpClrActChanged();
    partial void OnExpOfstActChanging(string value);
    partial void OnExpOfstActChanged();
    partial void OnobjTypeChanging(string value);
    partial void OnobjTypeChanged();
    partial void OnlogInstancChanging(System.Nullable<int> value);
    partial void OnlogInstancChanged();
    partial void OncreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OncreateDateChanged();
    partial void OnuserSign2Changing(System.Nullable<short> value);
    partial void OnuserSign2Changed();
    partial void OnupdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnupdateDateChanged();
    partial void OnARCMActChanging(string value);
    partial void OnARCMActChanged();
    partial void OnARCMFrnActChanging(string value);
    partial void OnARCMFrnActChanged();
    partial void OnARCMEUActChanging(string value);
    partial void OnARCMEUActChanged();
    partial void OnARCMExpActChanging(string value);
    partial void OnARCMExpActChanged();
    partial void OnAPCMActChanging(string value);
    partial void OnAPCMActChanged();
    partial void OnAPCMFrnActChanging(string value);
    partial void OnAPCMFrnActChanged();
    partial void OnAPCMEUActChanging(string value);
    partial void OnAPCMEUActChanged();
    partial void OnRevRetActChanging(string value);
    partial void OnRevRetActChanged();
    partial void OnBPLidChanging(System.Nullable<int> value);
    partial void OnBPLidChanged();
    partial void OnOwnerCodeChanging(System.Nullable<char> value);
    partial void OnOwnerCodeChanged();
    partial void OnNegStckActChanging(string value);
    partial void OnNegStckActChanged();
    partial void OnStkInTnActChanging(string value);
    partial void OnStkInTnActChanged();
    partial void OnAddrTypeChanging(string value);
    partial void OnAddrTypeChanged();
    partial void OnStreetNoChanging(string value);
    partial void OnStreetNoChanged();
    partial void OnPurBalActChanging(string value);
    partial void OnPurBalActChanged();
    partial void OnExcisableChanging(System.Nullable<char> value);
    partial void OnExcisableChanged();
    partial void OnWhICenActChanging(string value);
    partial void OnWhICenActChanged();
    partial void OnWhOCenActChanging(string value);
    partial void OnWhOCenActChanged();
    partial void OnWhShipToChanging(string value);
    partial void OnWhShipToChanged();
    partial void OnWipOffsetChanging(string value);
    partial void OnWipOffsetChanged();
    partial void OnStockOffstChanging(string value);
    partial void OnStockOffstChanged();
    partial void OnStorKeeperChanging(System.Nullable<int> value);
    partial void OnStorKeeperChanged();
    partial void OnShipperChanging(string value);
    partial void OnShipperChanged();
    partial void OnBinActivatChanging(System.Nullable<char> value);
    partial void OnBinActivatChanged();
    partial void OnBinSeptorChanging(string value);
    partial void OnBinSeptorChanged();
    partial void OnDftBinAbsChanging(System.Nullable<int> value);
    partial void OnDftBinAbsChanged();
    partial void OnDftBinEnfdChanging(System.Nullable<char> value);
    partial void OnDftBinEnfdChanged();
    partial void OnAutoIssMtdChanging(System.Nullable<short> value);
    partial void OnAutoIssMtdChanged();
    partial void OnManageSnBChanging(System.Nullable<char> value);
    partial void OnManageSnBChanged();
    partial void OnRecItemsByChanging(System.Nullable<short> value);
    partial void OnRecItemsByChanged();
    partial void OnRecBinEnabChanging(System.Nullable<char> value);
    partial void OnRecBinEnabChanged();
    partial void OnGlblLocNumChanging(string value);
    partial void OnGlblLocNumChanged();
    partial void OnRecvEmpBinChanging(System.Nullable<char> value);
    partial void OnRecvEmpBinChanged();
    partial void OnInactiveChanging(System.Nullable<char> value);
    partial void OnInactiveChanged();
    partial void OnRecvMaxQtyChanging(System.Nullable<char> value);
    partial void OnRecvMaxQtyChanged();
    partial void OnAutoRecvMdChanging(System.Nullable<short> value);
    partial void OnAutoRecvMdChanged();
    partial void OnRecvMaxWTChanging(System.Nullable<char> value);
    partial void OnRecvMaxWTChanged();
    partial void OnRecvUpToChanging(string value);
    partial void OnRecvUpToChanged();
    partial void OnFreeChrgSAChanging(string value);
    partial void OnFreeChrgSAChanged();
    partial void OnFreeChrgPUChanging(string value);
    partial void OnFreeChrgPUChanged();
    #endregion
		
		public OWH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhsCode", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WhsCode
		{
			get
			{
				return this._WhsCode;
			}
			set
			{
				if ((this._WhsCode != value))
				{
					this.OnWhsCodeChanging(value);
					this.SendPropertyChanging();
					this._WhsCode = value;
					this.SendPropertyChanged("WhsCode");
					this.OnWhsCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhsName", DbType="NVarChar(100)")]
		public string WhsName
		{
			get
			{
				return this._WhsName;
			}
			set
			{
				if ((this._WhsName != value))
				{
					this.OnWhsNameChanging(value);
					this.SendPropertyChanging();
					this._WhsName = value;
					this.SendPropertyChanged("WhsName");
					this.OnWhsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntrnalKey", DbType="Int")]
		public System.Nullable<int> IntrnalKey
		{
			get
			{
				return this._IntrnalKey;
			}
			set
			{
				if ((this._IntrnalKey != value))
				{
					this.OnIntrnalKeyChanging(value);
					this.SendPropertyChanging();
					this._IntrnalKey = value;
					this.SendPropertyChanged("IntrnalKey");
					this.OnIntrnalKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grp_Code", DbType="NVarChar(4)")]
		public string Grp_Code
		{
			get
			{
				return this._Grp_Code;
			}
			set
			{
				if ((this._Grp_Code != value))
				{
					this.OnGrp_CodeChanging(value);
					this.SendPropertyChanging();
					this._Grp_Code = value;
					this.SendPropertyChanged("Grp_Code");
					this.OnGrp_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BalInvntAc", DbType="NVarChar(15)")]
		public string BalInvntAc
		{
			get
			{
				return this._BalInvntAc;
			}
			set
			{
				if ((this._BalInvntAc != value))
				{
					this.OnBalInvntAcChanging(value);
					this.SendPropertyChanging();
					this._BalInvntAc = value;
					this.SendPropertyChanged("BalInvntAc");
					this.OnBalInvntAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaleCostAc", DbType="NVarChar(15)")]
		public string SaleCostAc
		{
			get
			{
				return this._SaleCostAc;
			}
			set
			{
				if ((this._SaleCostAc != value))
				{
					this.OnSaleCostAcChanging(value);
					this.SendPropertyChanging();
					this._SaleCostAc = value;
					this.SendPropertyChanged("SaleCostAc");
					this.OnSaleCostAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransferAc", DbType="NVarChar(15)")]
		public string TransferAc
		{
			get
			{
				return this._TransferAc;
			}
			set
			{
				if ((this._TransferAc != value))
				{
					this.OnTransferAcChanging(value);
					this.SendPropertyChanging();
					this._TransferAc = value;
					this.SendPropertyChanged("TransferAc");
					this.OnTransferAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Locked", DbType="Char(1)")]
		public System.Nullable<char> Locked
		{
			get
			{
				return this._Locked;
			}
			set
			{
				if ((this._Locked != value))
				{
					this.OnLockedChanging(value);
					this.SendPropertyChanging();
					this._Locked = value;
					this.SendPropertyChanged("Locked");
					this.OnLockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataSource", DbType="Char(1)")]
		public System.Nullable<char> DataSource
		{
			get
			{
				return this._DataSource;
			}
			set
			{
				if ((this._DataSource != value))
				{
					this.OnDataSourceChanging(value);
					this.SendPropertyChanging();
					this._DataSource = value;
					this.SendPropertyChanged("DataSource");
					this.OnDataSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserSign", DbType="SmallInt")]
		public System.Nullable<short> UserSign
		{
			get
			{
				return this._UserSign;
			}
			set
			{
				if ((this._UserSign != value))
				{
					this.OnUserSignChanging(value);
					this.SendPropertyChanging();
					this._UserSign = value;
					this.SendPropertyChanged("UserSign");
					this.OnUserSignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RevenuesAc", DbType="NVarChar(15)")]
		public string RevenuesAc
		{
			get
			{
				return this._RevenuesAc;
			}
			set
			{
				if ((this._RevenuesAc != value))
				{
					this.OnRevenuesAcChanging(value);
					this.SendPropertyChanging();
					this._RevenuesAc = value;
					this.SendPropertyChanged("RevenuesAc");
					this.OnRevenuesAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VarianceAc", DbType="NVarChar(15)")]
		public string VarianceAc
		{
			get
			{
				return this._VarianceAc;
			}
			set
			{
				if ((this._VarianceAc != value))
				{
					this.OnVarianceAcChanging(value);
					this.SendPropertyChanging();
					this._VarianceAc = value;
					this.SendPropertyChanged("VarianceAc");
					this.OnVarianceAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DecreasAc", DbType="NVarChar(15)")]
		public string DecreasAc
		{
			get
			{
				return this._DecreasAc;
			}
			set
			{
				if ((this._DecreasAc != value))
				{
					this.OnDecreasAcChanging(value);
					this.SendPropertyChanging();
					this._DecreasAc = value;
					this.SendPropertyChanged("DecreasAc");
					this.OnDecreasAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncreasAc", DbType="NVarChar(15)")]
		public string IncreasAc
		{
			get
			{
				return this._IncreasAc;
			}
			set
			{
				if ((this._IncreasAc != value))
				{
					this.OnIncreasAcChanging(value);
					this.SendPropertyChanging();
					this._IncreasAc = value;
					this.SendPropertyChanged("IncreasAc");
					this.OnIncreasAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReturnAc", DbType="NVarChar(15)")]
		public string ReturnAc
		{
			get
			{
				return this._ReturnAc;
			}
			set
			{
				if ((this._ReturnAc != value))
				{
					this.OnReturnAcChanging(value);
					this.SendPropertyChanging();
					this._ReturnAc = value;
					this.SendPropertyChanged("ReturnAc");
					this.OnReturnAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpensesAc", DbType="NVarChar(15)")]
		public string ExpensesAc
		{
			get
			{
				return this._ExpensesAc;
			}
			set
			{
				if ((this._ExpensesAc != value))
				{
					this.OnExpensesAcChanging(value);
					this.SendPropertyChanging();
					this._ExpensesAc = value;
					this.SendPropertyChanged("ExpensesAc");
					this.OnExpensesAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EURevenuAc", DbType="NVarChar(15)")]
		public string EURevenuAc
		{
			get
			{
				return this._EURevenuAc;
			}
			set
			{
				if ((this._EURevenuAc != value))
				{
					this.OnEURevenuAcChanging(value);
					this.SendPropertyChanging();
					this._EURevenuAc = value;
					this.SendPropertyChanged("EURevenuAc");
					this.OnEURevenuAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EUExpensAc", DbType="NVarChar(15)")]
		public string EUExpensAc
		{
			get
			{
				return this._EUExpensAc;
			}
			set
			{
				if ((this._EUExpensAc != value))
				{
					this.OnEUExpensAcChanging(value);
					this.SendPropertyChanging();
					this._EUExpensAc = value;
					this.SendPropertyChanged("EUExpensAc");
					this.OnEUExpensAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrRevenuAc", DbType="NVarChar(15)")]
		public string FrRevenuAc
		{
			get
			{
				return this._FrRevenuAc;
			}
			set
			{
				if ((this._FrRevenuAc != value))
				{
					this.OnFrRevenuAcChanging(value);
					this.SendPropertyChanging();
					this._FrRevenuAc = value;
					this.SendPropertyChanged("FrRevenuAc");
					this.OnFrRevenuAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrExpensAc", DbType="NVarChar(15)")]
		public string FrExpensAc
		{
			get
			{
				return this._FrExpensAc;
			}
			set
			{
				if ((this._FrExpensAc != value))
				{
					this.OnFrExpensAcChanging(value);
					this.SendPropertyChanging();
					this._FrExpensAc = value;
					this.SendPropertyChanged("FrExpensAc");
					this.OnFrExpensAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VatGroup", DbType="NVarChar(8)")]
		public string VatGroup
		{
			get
			{
				return this._VatGroup;
			}
			set
			{
				if ((this._VatGroup != value))
				{
					this.OnVatGroupChanging(value);
					this.SendPropertyChanging();
					this._VatGroup = value;
					this.SendPropertyChanged("VatGroup");
					this.OnVatGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="NVarChar(100)")]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this.OnStreetChanging(value);
					this.SendPropertyChanging();
					this._Street = value;
					this.SendPropertyChanged("Street");
					this.OnStreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Block", DbType="NVarChar(100)")]
		public string Block
		{
			get
			{
				return this._Block;
			}
			set
			{
				if ((this._Block != value))
				{
					this.OnBlockChanging(value);
					this.SendPropertyChanging();
					this._Block = value;
					this.SendPropertyChanged("Block");
					this.OnBlockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode", DbType="NVarChar(20)")]
		public string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				if ((this._ZipCode != value))
				{
					this.OnZipCodeChanging(value);
					this.SendPropertyChanging();
					this._ZipCode = value;
					this.SendPropertyChanged("ZipCode");
					this.OnZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(100)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_County", DbType="NVarChar(100)")]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this.OnCountyChanging(value);
					this.SendPropertyChanging();
					this._County = value;
					this.SendPropertyChanged("County");
					this.OnCountyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(3)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(3)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="Int")]
		public System.Nullable<int> Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DropShip", DbType="Char(1)")]
		public System.Nullable<char> DropShip
		{
			get
			{
				return this._DropShip;
			}
			set
			{
				if ((this._DropShip != value))
				{
					this.OnDropShipChanging(value);
					this.SendPropertyChanging();
					this._DropShip = value;
					this.SendPropertyChanged("DropShip");
					this.OnDropShipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExmptIncom", DbType="NVarChar(15)")]
		public string ExmptIncom
		{
			get
			{
				return this._ExmptIncom;
			}
			set
			{
				if ((this._ExmptIncom != value))
				{
					this.OnExmptIncomChanging(value);
					this.SendPropertyChanging();
					this._ExmptIncom = value;
					this.SendPropertyChanged("ExmptIncom");
					this.OnExmptIncomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseTax", DbType="Char(1)")]
		public System.Nullable<char> UseTax
		{
			get
			{
				return this._UseTax;
			}
			set
			{
				if ((this._UseTax != value))
				{
					this.OnUseTaxChanging(value);
					this.SendPropertyChanging();
					this._UseTax = value;
					this.SendPropertyChanged("UseTax");
					this.OnUseTaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceDifAc", DbType="NVarChar(15)")]
		public string PriceDifAc
		{
			get
			{
				return this._PriceDifAc;
			}
			set
			{
				if ((this._PriceDifAc != value))
				{
					this.OnPriceDifAcChanging(value);
					this.SendPropertyChanging();
					this._PriceDifAc = value;
					this.SendPropertyChanged("PriceDifAc");
					this.OnPriceDifAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExchangeAc", DbType="NVarChar(15)")]
		public string ExchangeAc
		{
			get
			{
				return this._ExchangeAc;
			}
			set
			{
				if ((this._ExchangeAc != value))
				{
					this.OnExchangeAcChanging(value);
					this.SendPropertyChanging();
					this._ExchangeAc = value;
					this.SendPropertyChanged("ExchangeAc");
					this.OnExchangeAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BalanceAcc", DbType="NVarChar(15)")]
		public string BalanceAcc
		{
			get
			{
				return this._BalanceAcc;
			}
			set
			{
				if ((this._BalanceAcc != value))
				{
					this.OnBalanceAccChanging(value);
					this.SendPropertyChanging();
					this._BalanceAcc = value;
					this.SendPropertyChanged("BalanceAcc");
					this.OnBalanceAccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchaseAc", DbType="NVarChar(15)")]
		public string PurchaseAc
		{
			get
			{
				return this._PurchaseAc;
			}
			set
			{
				if ((this._PurchaseAc != value))
				{
					this.OnPurchaseAcChanging(value);
					this.SendPropertyChanging();
					this._PurchaseAc = value;
					this.SendPropertyChanged("PurchaseAc");
					this.OnPurchaseAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAReturnAc", DbType="NVarChar(15)")]
		public string PAReturnAc
		{
			get
			{
				return this._PAReturnAc;
			}
			set
			{
				if ((this._PAReturnAc != value))
				{
					this.OnPAReturnAcChanging(value);
					this.SendPropertyChanging();
					this._PAReturnAc = value;
					this.SendPropertyChanged("PAReturnAc");
					this.OnPAReturnAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchOfsAc", DbType="NVarChar(15)")]
		public string PurchOfsAc
		{
			get
			{
				return this._PurchOfsAc;
			}
			set
			{
				if ((this._PurchOfsAc != value))
				{
					this.OnPurchOfsAcChanging(value);
					this.SendPropertyChanging();
					this._PurchOfsAc = value;
					this.SendPropertyChanged("PurchOfsAc");
					this.OnPurchOfsAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FedTaxID", DbType="NVarChar(32)")]
		public string FedTaxID
		{
			get
			{
				return this._FedTaxID;
			}
			set
			{
				if ((this._FedTaxID != value))
				{
					this.OnFedTaxIDChanging(value);
					this.SendPropertyChanging();
					this._FedTaxID = value;
					this.SendPropertyChanged("FedTaxID");
					this.OnFedTaxIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Building", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Building
		{
			get
			{
				return this._Building;
			}
			set
			{
				if ((this._Building != value))
				{
					this.OnBuildingChanging(value);
					this.SendPropertyChanging();
					this._Building = value;
					this.SendPropertyChanged("Building");
					this.OnBuildingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShpdGdsAct", DbType="NVarChar(15)")]
		public string ShpdGdsAct
		{
			get
			{
				return this._ShpdGdsAct;
			}
			set
			{
				if ((this._ShpdGdsAct != value))
				{
					this.OnShpdGdsActChanging(value);
					this.SendPropertyChanging();
					this._ShpdGdsAct = value;
					this.SendPropertyChanged("ShpdGdsAct");
					this.OnShpdGdsActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VatRevAct", DbType="NVarChar(15)")]
		public string VatRevAct
		{
			get
			{
				return this._VatRevAct;
			}
			set
			{
				if ((this._VatRevAct != value))
				{
					this.OnVatRevActChanging(value);
					this.SendPropertyChanging();
					this._VatRevAct = value;
					this.SendPropertyChanged("VatRevAct");
					this.OnVatRevActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DecresGlAc", DbType="NVarChar(15)")]
		public string DecresGlAc
		{
			get
			{
				return this._DecresGlAc;
			}
			set
			{
				if ((this._DecresGlAc != value))
				{
					this.OnDecresGlAcChanging(value);
					this.SendPropertyChanging();
					this._DecresGlAc = value;
					this.SendPropertyChanged("DecresGlAc");
					this.OnDecresGlAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncresGlAc", DbType="NVarChar(15)")]
		public string IncresGlAc
		{
			get
			{
				return this._IncresGlAc;
			}
			set
			{
				if ((this._IncresGlAc != value))
				{
					this.OnIncresGlAcChanging(value);
					this.SendPropertyChanging();
					this._IncresGlAc = value;
					this.SendPropertyChanged("IncresGlAc");
					this.OnIncresGlAcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nettable", DbType="Char(1)")]
		public System.Nullable<char> Nettable
		{
			get
			{
				return this._Nettable;
			}
			set
			{
				if ((this._Nettable != value))
				{
					this.OnNettableChanging(value);
					this.SendPropertyChanging();
					this._Nettable = value;
					this.SendPropertyChanged("Nettable");
					this.OnNettableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokRvlAct", DbType="NVarChar(15)")]
		public string StokRvlAct
		{
			get
			{
				return this._StokRvlAct;
			}
			set
			{
				if ((this._StokRvlAct != value))
				{
					this.OnStokRvlActChanging(value);
					this.SendPropertyChanging();
					this._StokRvlAct = value;
					this.SendPropertyChanged("StokRvlAct");
					this.OnStokRvlActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StkOffsAct", DbType="NVarChar(15)")]
		public string StkOffsAct
		{
			get
			{
				return this._StkOffsAct;
			}
			set
			{
				if ((this._StkOffsAct != value))
				{
					this.OnStkOffsActChanging(value);
					this.SendPropertyChanging();
					this._StkOffsAct = value;
					this.SendPropertyChanged("StkOffsAct");
					this.OnStkOffsActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WipAcct", DbType="NVarChar(15)")]
		public string WipAcct
		{
			get
			{
				return this._WipAcct;
			}
			set
			{
				if ((this._WipAcct != value))
				{
					this.OnWipAcctChanging(value);
					this.SendPropertyChanging();
					this._WipAcct = value;
					this.SendPropertyChanged("WipAcct");
					this.OnWipAcctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WipVarAcct", DbType="NVarChar(15)")]
		public string WipVarAcct
		{
			get
			{
				return this._WipVarAcct;
			}
			set
			{
				if ((this._WipVarAcct != value))
				{
					this.OnWipVarAcctChanging(value);
					this.SendPropertyChanging();
					this._WipVarAcct = value;
					this.SendPropertyChanged("WipVarAcct");
					this.OnWipVarAcctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostRvlAct", DbType="NVarChar(15)")]
		public string CostRvlAct
		{
			get
			{
				return this._CostRvlAct;
			}
			set
			{
				if ((this._CostRvlAct != value))
				{
					this.OnCostRvlActChanging(value);
					this.SendPropertyChanging();
					this._CostRvlAct = value;
					this.SendPropertyChanged("CostRvlAct");
					this.OnCostRvlActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CstOffsAct", DbType="NVarChar(15)")]
		public string CstOffsAct
		{
			get
			{
				return this._CstOffsAct;
			}
			set
			{
				if ((this._CstOffsAct != value))
				{
					this.OnCstOffsActChanging(value);
					this.SendPropertyChanging();
					this._CstOffsAct = value;
					this.SendPropertyChanged("CstOffsAct");
					this.OnCstOffsActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpClrAct", DbType="NVarChar(15)")]
		public string ExpClrAct
		{
			get
			{
				return this._ExpClrAct;
			}
			set
			{
				if ((this._ExpClrAct != value))
				{
					this.OnExpClrActChanging(value);
					this.SendPropertyChanging();
					this._ExpClrAct = value;
					this.SendPropertyChanged("ExpClrAct");
					this.OnExpClrActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpOfstAct", DbType="NVarChar(15)")]
		public string ExpOfstAct
		{
			get
			{
				return this._ExpOfstAct;
			}
			set
			{
				if ((this._ExpOfstAct != value))
				{
					this.OnExpOfstActChanging(value);
					this.SendPropertyChanging();
					this._ExpOfstAct = value;
					this.SendPropertyChanged("ExpOfstAct");
					this.OnExpOfstActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_objType", DbType="NVarChar(20)")]
		public string objType
		{
			get
			{
				return this._objType;
			}
			set
			{
				if ((this._objType != value))
				{
					this.OnobjTypeChanging(value);
					this.SendPropertyChanging();
					this._objType = value;
					this.SendPropertyChanged("objType");
					this.OnobjTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logInstanc", DbType="Int")]
		public System.Nullable<int> logInstanc
		{
			get
			{
				return this._logInstanc;
			}
			set
			{
				if ((this._logInstanc != value))
				{
					this.OnlogInstancChanging(value);
					this.SendPropertyChanging();
					this._logInstanc = value;
					this.SendPropertyChanged("logInstanc");
					this.OnlogInstancChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userSign2", DbType="SmallInt")]
		public System.Nullable<short> userSign2
		{
			get
			{
				return this._userSign2;
			}
			set
			{
				if ((this._userSign2 != value))
				{
					this.OnuserSign2Changing(value);
					this.SendPropertyChanging();
					this._userSign2 = value;
					this.SendPropertyChanged("userSign2");
					this.OnuserSign2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> updateDate
		{
			get
			{
				return this._updateDate;
			}
			set
			{
				if ((this._updateDate != value))
				{
					this.OnupdateDateChanging(value);
					this.SendPropertyChanging();
					this._updateDate = value;
					this.SendPropertyChanged("updateDate");
					this.OnupdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARCMAct", DbType="NVarChar(15)")]
		public string ARCMAct
		{
			get
			{
				return this._ARCMAct;
			}
			set
			{
				if ((this._ARCMAct != value))
				{
					this.OnARCMActChanging(value);
					this.SendPropertyChanging();
					this._ARCMAct = value;
					this.SendPropertyChanged("ARCMAct");
					this.OnARCMActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARCMFrnAct", DbType="NVarChar(15)")]
		public string ARCMFrnAct
		{
			get
			{
				return this._ARCMFrnAct;
			}
			set
			{
				if ((this._ARCMFrnAct != value))
				{
					this.OnARCMFrnActChanging(value);
					this.SendPropertyChanging();
					this._ARCMFrnAct = value;
					this.SendPropertyChanged("ARCMFrnAct");
					this.OnARCMFrnActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARCMEUAct", DbType="NVarChar(15)")]
		public string ARCMEUAct
		{
			get
			{
				return this._ARCMEUAct;
			}
			set
			{
				if ((this._ARCMEUAct != value))
				{
					this.OnARCMEUActChanging(value);
					this.SendPropertyChanging();
					this._ARCMEUAct = value;
					this.SendPropertyChanged("ARCMEUAct");
					this.OnARCMEUActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARCMExpAct", DbType="NVarChar(15)")]
		public string ARCMExpAct
		{
			get
			{
				return this._ARCMExpAct;
			}
			set
			{
				if ((this._ARCMExpAct != value))
				{
					this.OnARCMExpActChanging(value);
					this.SendPropertyChanging();
					this._ARCMExpAct = value;
					this.SendPropertyChanged("ARCMExpAct");
					this.OnARCMExpActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APCMAct", DbType="NVarChar(15)")]
		public string APCMAct
		{
			get
			{
				return this._APCMAct;
			}
			set
			{
				if ((this._APCMAct != value))
				{
					this.OnAPCMActChanging(value);
					this.SendPropertyChanging();
					this._APCMAct = value;
					this.SendPropertyChanged("APCMAct");
					this.OnAPCMActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APCMFrnAct", DbType="NVarChar(15)")]
		public string APCMFrnAct
		{
			get
			{
				return this._APCMFrnAct;
			}
			set
			{
				if ((this._APCMFrnAct != value))
				{
					this.OnAPCMFrnActChanging(value);
					this.SendPropertyChanging();
					this._APCMFrnAct = value;
					this.SendPropertyChanged("APCMFrnAct");
					this.OnAPCMFrnActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APCMEUAct", DbType="NVarChar(15)")]
		public string APCMEUAct
		{
			get
			{
				return this._APCMEUAct;
			}
			set
			{
				if ((this._APCMEUAct != value))
				{
					this.OnAPCMEUActChanging(value);
					this.SendPropertyChanging();
					this._APCMEUAct = value;
					this.SendPropertyChanged("APCMEUAct");
					this.OnAPCMEUActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RevRetAct", DbType="NVarChar(15)")]
		public string RevRetAct
		{
			get
			{
				return this._RevRetAct;
			}
			set
			{
				if ((this._RevRetAct != value))
				{
					this.OnRevRetActChanging(value);
					this.SendPropertyChanging();
					this._RevRetAct = value;
					this.SendPropertyChanged("RevRetAct");
					this.OnRevRetActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BPLid", DbType="Int")]
		public System.Nullable<int> BPLid
		{
			get
			{
				return this._BPLid;
			}
			set
			{
				if ((this._BPLid != value))
				{
					this.OnBPLidChanging(value);
					this.SendPropertyChanging();
					this._BPLid = value;
					this.SendPropertyChanged("BPLid");
					this.OnBPLidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerCode", DbType="Char(1)")]
		public System.Nullable<char> OwnerCode
		{
			get
			{
				return this._OwnerCode;
			}
			set
			{
				if ((this._OwnerCode != value))
				{
					this.OnOwnerCodeChanging(value);
					this.SendPropertyChanging();
					this._OwnerCode = value;
					this.SendPropertyChanged("OwnerCode");
					this.OnOwnerCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NegStckAct", DbType="NVarChar(15)")]
		public string NegStckAct
		{
			get
			{
				return this._NegStckAct;
			}
			set
			{
				if ((this._NegStckAct != value))
				{
					this.OnNegStckActChanging(value);
					this.SendPropertyChanging();
					this._NegStckAct = value;
					this.SendPropertyChanged("NegStckAct");
					this.OnNegStckActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StkInTnAct", DbType="NVarChar(15)")]
		public string StkInTnAct
		{
			get
			{
				return this._StkInTnAct;
			}
			set
			{
				if ((this._StkInTnAct != value))
				{
					this.OnStkInTnActChanging(value);
					this.SendPropertyChanging();
					this._StkInTnAct = value;
					this.SendPropertyChanged("StkInTnAct");
					this.OnStkInTnActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddrType", DbType="NVarChar(100)")]
		public string AddrType
		{
			get
			{
				return this._AddrType;
			}
			set
			{
				if ((this._AddrType != value))
				{
					this.OnAddrTypeChanging(value);
					this.SendPropertyChanging();
					this._AddrType = value;
					this.SendPropertyChanged("AddrType");
					this.OnAddrTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetNo", DbType="NVarChar(100)")]
		public string StreetNo
		{
			get
			{
				return this._StreetNo;
			}
			set
			{
				if ((this._StreetNo != value))
				{
					this.OnStreetNoChanging(value);
					this.SendPropertyChanging();
					this._StreetNo = value;
					this.SendPropertyChanged("StreetNo");
					this.OnStreetNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurBalAct", DbType="NVarChar(15)")]
		public string PurBalAct
		{
			get
			{
				return this._PurBalAct;
			}
			set
			{
				if ((this._PurBalAct != value))
				{
					this.OnPurBalActChanging(value);
					this.SendPropertyChanging();
					this._PurBalAct = value;
					this.SendPropertyChanged("PurBalAct");
					this.OnPurBalActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Excisable", DbType="Char(1)")]
		public System.Nullable<char> Excisable
		{
			get
			{
				return this._Excisable;
			}
			set
			{
				if ((this._Excisable != value))
				{
					this.OnExcisableChanging(value);
					this.SendPropertyChanging();
					this._Excisable = value;
					this.SendPropertyChanged("Excisable");
					this.OnExcisableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhICenAct", DbType="NVarChar(15)")]
		public string WhICenAct
		{
			get
			{
				return this._WhICenAct;
			}
			set
			{
				if ((this._WhICenAct != value))
				{
					this.OnWhICenActChanging(value);
					this.SendPropertyChanging();
					this._WhICenAct = value;
					this.SendPropertyChanged("WhICenAct");
					this.OnWhICenActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhOCenAct", DbType="NVarChar(15)")]
		public string WhOCenAct
		{
			get
			{
				return this._WhOCenAct;
			}
			set
			{
				if ((this._WhOCenAct != value))
				{
					this.OnWhOCenActChanging(value);
					this.SendPropertyChanging();
					this._WhOCenAct = value;
					this.SendPropertyChanged("WhOCenAct");
					this.OnWhOCenActChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhShipTo", DbType="NVarChar(100)")]
		public string WhShipTo
		{
			get
			{
				return this._WhShipTo;
			}
			set
			{
				if ((this._WhShipTo != value))
				{
					this.OnWhShipToChanging(value);
					this.SendPropertyChanging();
					this._WhShipTo = value;
					this.SendPropertyChanged("WhShipTo");
					this.OnWhShipToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WipOffset", DbType="NVarChar(15)")]
		public string WipOffset
		{
			get
			{
				return this._WipOffset;
			}
			set
			{
				if ((this._WipOffset != value))
				{
					this.OnWipOffsetChanging(value);
					this.SendPropertyChanging();
					this._WipOffset = value;
					this.SendPropertyChanged("WipOffset");
					this.OnWipOffsetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockOffst", DbType="NVarChar(15)")]
		public string StockOffst
		{
			get
			{
				return this._StockOffst;
			}
			set
			{
				if ((this._StockOffst != value))
				{
					this.OnStockOffstChanging(value);
					this.SendPropertyChanging();
					this._StockOffst = value;
					this.SendPropertyChanged("StockOffst");
					this.OnStockOffstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StorKeeper", DbType="Int")]
		public System.Nullable<int> StorKeeper
		{
			get
			{
				return this._StorKeeper;
			}
			set
			{
				if ((this._StorKeeper != value))
				{
					this.OnStorKeeperChanging(value);
					this.SendPropertyChanging();
					this._StorKeeper = value;
					this.SendPropertyChanged("StorKeeper");
					this.OnStorKeeperChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shipper", DbType="NVarChar(15)")]
		public string Shipper
		{
			get
			{
				return this._Shipper;
			}
			set
			{
				if ((this._Shipper != value))
				{
					this.OnShipperChanging(value);
					this.SendPropertyChanging();
					this._Shipper = value;
					this.SendPropertyChanged("Shipper");
					this.OnShipperChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BinActivat", DbType="Char(1)")]
		public System.Nullable<char> BinActivat
		{
			get
			{
				return this._BinActivat;
			}
			set
			{
				if ((this._BinActivat != value))
				{
					this.OnBinActivatChanging(value);
					this.SendPropertyChanging();
					this._BinActivat = value;
					this.SendPropertyChanged("BinActivat");
					this.OnBinActivatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BinSeptor", DbType="NVarChar(5)")]
		public string BinSeptor
		{
			get
			{
				return this._BinSeptor;
			}
			set
			{
				if ((this._BinSeptor != value))
				{
					this.OnBinSeptorChanging(value);
					this.SendPropertyChanging();
					this._BinSeptor = value;
					this.SendPropertyChanged("BinSeptor");
					this.OnBinSeptorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DftBinAbs", DbType="Int")]
		public System.Nullable<int> DftBinAbs
		{
			get
			{
				return this._DftBinAbs;
			}
			set
			{
				if ((this._DftBinAbs != value))
				{
					this.OnDftBinAbsChanging(value);
					this.SendPropertyChanging();
					this._DftBinAbs = value;
					this.SendPropertyChanged("DftBinAbs");
					this.OnDftBinAbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DftBinEnfd", DbType="Char(1)")]
		public System.Nullable<char> DftBinEnfd
		{
			get
			{
				return this._DftBinEnfd;
			}
			set
			{
				if ((this._DftBinEnfd != value))
				{
					this.OnDftBinEnfdChanging(value);
					this.SendPropertyChanging();
					this._DftBinEnfd = value;
					this.SendPropertyChanged("DftBinEnfd");
					this.OnDftBinEnfdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoIssMtd", DbType="SmallInt")]
		public System.Nullable<short> AutoIssMtd
		{
			get
			{
				return this._AutoIssMtd;
			}
			set
			{
				if ((this._AutoIssMtd != value))
				{
					this.OnAutoIssMtdChanging(value);
					this.SendPropertyChanging();
					this._AutoIssMtd = value;
					this.SendPropertyChanged("AutoIssMtd");
					this.OnAutoIssMtdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManageSnB", DbType="Char(1)")]
		public System.Nullable<char> ManageSnB
		{
			get
			{
				return this._ManageSnB;
			}
			set
			{
				if ((this._ManageSnB != value))
				{
					this.OnManageSnBChanging(value);
					this.SendPropertyChanging();
					this._ManageSnB = value;
					this.SendPropertyChanged("ManageSnB");
					this.OnManageSnBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecItemsBy", DbType="SmallInt")]
		public System.Nullable<short> RecItemsBy
		{
			get
			{
				return this._RecItemsBy;
			}
			set
			{
				if ((this._RecItemsBy != value))
				{
					this.OnRecItemsByChanging(value);
					this.SendPropertyChanging();
					this._RecItemsBy = value;
					this.SendPropertyChanged("RecItemsBy");
					this.OnRecItemsByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecBinEnab", DbType="Char(1)")]
		public System.Nullable<char> RecBinEnab
		{
			get
			{
				return this._RecBinEnab;
			}
			set
			{
				if ((this._RecBinEnab != value))
				{
					this.OnRecBinEnabChanging(value);
					this.SendPropertyChanging();
					this._RecBinEnab = value;
					this.SendPropertyChanged("RecBinEnab");
					this.OnRecBinEnabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GlblLocNum", DbType="NVarChar(50)")]
		public string GlblLocNum
		{
			get
			{
				return this._GlblLocNum;
			}
			set
			{
				if ((this._GlblLocNum != value))
				{
					this.OnGlblLocNumChanging(value);
					this.SendPropertyChanging();
					this._GlblLocNum = value;
					this.SendPropertyChanged("GlblLocNum");
					this.OnGlblLocNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecvEmpBin", DbType="Char(1)")]
		public System.Nullable<char> RecvEmpBin
		{
			get
			{
				return this._RecvEmpBin;
			}
			set
			{
				if ((this._RecvEmpBin != value))
				{
					this.OnRecvEmpBinChanging(value);
					this.SendPropertyChanging();
					this._RecvEmpBin = value;
					this.SendPropertyChanged("RecvEmpBin");
					this.OnRecvEmpBinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inactive", DbType="Char(1)")]
		public System.Nullable<char> Inactive
		{
			get
			{
				return this._Inactive;
			}
			set
			{
				if ((this._Inactive != value))
				{
					this.OnInactiveChanging(value);
					this.SendPropertyChanging();
					this._Inactive = value;
					this.SendPropertyChanged("Inactive");
					this.OnInactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecvMaxQty", DbType="Char(1)")]
		public System.Nullable<char> RecvMaxQty
		{
			get
			{
				return this._RecvMaxQty;
			}
			set
			{
				if ((this._RecvMaxQty != value))
				{
					this.OnRecvMaxQtyChanging(value);
					this.SendPropertyChanging();
					this._RecvMaxQty = value;
					this.SendPropertyChanged("RecvMaxQty");
					this.OnRecvMaxQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoRecvMd", DbType="SmallInt")]
		public System.Nullable<short> AutoRecvMd
		{
			get
			{
				return this._AutoRecvMd;
			}
			set
			{
				if ((this._AutoRecvMd != value))
				{
					this.OnAutoRecvMdChanging(value);
					this.SendPropertyChanging();
					this._AutoRecvMd = value;
					this.SendPropertyChanged("AutoRecvMd");
					this.OnAutoRecvMdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecvMaxWT", DbType="Char(1)")]
		public System.Nullable<char> RecvMaxWT
		{
			get
			{
				return this._RecvMaxWT;
			}
			set
			{
				if ((this._RecvMaxWT != value))
				{
					this.OnRecvMaxWTChanging(value);
					this.SendPropertyChanging();
					this._RecvMaxWT = value;
					this.SendPropertyChanged("RecvMaxWT");
					this.OnRecvMaxWTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecvUpTo", DbType="NVarChar(6)")]
		public string RecvUpTo
		{
			get
			{
				return this._RecvUpTo;
			}
			set
			{
				if ((this._RecvUpTo != value))
				{
					this.OnRecvUpToChanging(value);
					this.SendPropertyChanging();
					this._RecvUpTo = value;
					this.SendPropertyChanged("RecvUpTo");
					this.OnRecvUpToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FreeChrgSA", DbType="NVarChar(15)")]
		public string FreeChrgSA
		{
			get
			{
				return this._FreeChrgSA;
			}
			set
			{
				if ((this._FreeChrgSA != value))
				{
					this.OnFreeChrgSAChanging(value);
					this.SendPropertyChanging();
					this._FreeChrgSA = value;
					this.SendPropertyChanged("FreeChrgSA");
					this.OnFreeChrgSAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FreeChrgPU", DbType="NVarChar(15)")]
		public string FreeChrgPU
		{
			get
			{
				return this._FreeChrgPU;
			}
			set
			{
				if ((this._FreeChrgPU != value))
				{
					this.OnFreeChrgPUChanging(value);
					this.SendPropertyChanging();
					this._FreeChrgPU = value;
					this.SendPropertyChanged("FreeChrgPU");
					this.OnFreeChrgPUChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
