<?xml version="1.0" encoding="utf-8"?><Database Name="US1" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PVGD50870739A\INS2;Initial Catalog=US1;User ID=sa" SettingsObjectName="WindowsFormsApplication2.Properties.Settings" SettingsPropertyName="US1ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.OBIN" Member="OBINs">
    <Type Name="OBIN">
      <Column Name="AbsEntry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BinCode" Type="System.String" DbType="NVarChar(228) NOT NULL" CanBeNull="false" />
      <Column Name="WhsCode" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="SysBin" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="SL1Abs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SL1Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SL2Abs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SL2Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SL3Abs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SL3Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SL4Abs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SL4Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Attr1Abs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Attr1Val" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Attr2Abs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Attr2Val" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Attr3Abs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Attr3Val" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Attr4Abs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Attr4Val" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Attr5Abs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Attr5Val" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Attr6Abs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Attr6Val" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Attr7Abs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Attr7Val" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Attr8Abs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Attr8Val" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Attr9Abs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Attr9Val" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Attr10Abs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Attr10Val" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Disabled" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Descr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BarCode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AltSortCod" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ItmRtrictT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SpcItmCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SpcItmGrpC" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SngBatch" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="RtrictType" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="RtrictResn" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="RtrictDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DataSource" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="UserSign" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Transfered" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Instance" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="LogInstanc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserSign2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="MinLevel" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="MaxLevel" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ReceiveBin" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NoAutoAllc" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="MaxWeight1" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Wght1Unit" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MaxWeight2" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Wght2Unit" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OWHS" Member="OWHs">
    <Type Name="OWH">
      <Column Name="WhsCode" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WhsName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IntrnalKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Grp_Code" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="BalInvntAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="SaleCostAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="TransferAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Locked" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DataSource" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="UserSign" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="RevenuesAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="VarianceAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="DecreasAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="IncreasAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ReturnAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ExpensesAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="EURevenuAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="EUExpensAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="FrRevenuAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="FrExpensAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="VatGroup" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="Street" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Block" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ZipCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="County" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="Location" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DropShip" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ExmptIncom" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="UseTax" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PriceDifAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ExchangeAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="BalanceAcc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PurchaseAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PAReturnAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PurchOfsAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="FedTaxID" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="Building" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ShpdGdsAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="VatRevAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="DecresGlAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="IncresGlAc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Nettable" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="StokRvlAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="StkOffsAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="WipAcct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="WipVarAcct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="CostRvlAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="CstOffsAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ExpClrAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ExpOfstAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="objType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="logInstanc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="createDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="userSign2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="updateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ARCMAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ARCMFrnAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ARCMEUAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ARCMExpAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="APCMAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="APCMFrnAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="APCMEUAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="RevRetAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="BPLid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerCode" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NegStckAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="StkInTnAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="AddrType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StreetNo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PurBalAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Excisable" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="WhICenAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="WhOCenAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="WhShipTo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="WipOffset" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="StockOffst" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="StorKeeper" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Shipper" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="BinActivat" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BinSeptor" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="DftBinAbs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DftBinEnfd" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="AutoIssMtd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ManageSnB" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="RecItemsBy" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="RecBinEnab" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="GlblLocNum" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RecvEmpBin" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Inactive" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="RecvMaxQty" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="AutoRecvMd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="RecvMaxWT" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="RecvUpTo" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="FreeChrgSA" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="FreeChrgPU" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
    </Type>
  </Table>
</Database>